pipelines:
  branches:
    master:
      - step:
          name: Build & Push Images
          image: alpine:latest
          services:
            - docker
          script:
            - apk add --no-cache bash curl jq
            - export SAM_VERSION="$(./sam-version.sh)"
            - export FULL_VERSION="${SAM_VERSION}-${BITBUCKET_BUILD_NUMBER}"

            # Base
            - docker build -t truemark/aws-sam-cli:${FULL_VERSION} .
            - docker tag truemark/aws-sam-cli:${FULL_VERSION} truemark/aws-sam-cli:latest

            # Golang
            - docker build --build-arg SOURCE_IMAGE="truemark/aws-sam-cli:${FULL_VERSION}" -t truemark/aws-sam-cli:golang-${FULL_VERSION} -f golang.Dockerfile .
            - docker tag truemark/aws-sam-cli:golang-${FULL_VERSION} truemark/aws-sam-cli:golang-${SAM_VERSION}
            - docker tag truemark/aws-sam-cli:golang-${FULL_VERSION} truemark/aws-sam-cli:golang

            # Golang Pipe
            - docker build --build-arg SOURCE_IMAGE="truemark/aws-sam-cli:golang-${FULL_VERSION}" -t truemark/aws-sam-cli-pipe:golang-${FULL_VERSION} -f pipe.Dockerfile .
            - docker tag truemark/aws-sam-cli-pipe:golang-${FULL_VERSION} truemark/aws-sam-cli-pipe:golang-${SAM_VERSION}
            - docker tag truemark/aws-sam-cli-pipe:golang-${FULL_VERSION} truemark/aws-sam-cli-pipe:golang

            # Node 14
            - docker build --build-arg SOURCE_IMAGE="truemark/aws-sam-cli:${FULL_VERSION}" -t truemark/aws-sam-cli:node-14-${FULL_VERSION} -f node-14.Dockerfile .
            - docker tag truemark/aws-sam-cli:node-14-${FULL_VERSION} truemark/aws-sam-cli:node-14-${SAM_VERSION}
            - docker tag truemark/aws-sam-cli:node-14-${FULL_VERSION} truemark/aws-sam-cli:node-14

            # Node 14 Pipe
            - docker build --build-arg SOURCE_IMAGE="truemark/aws-sam-cli:node-14-${FULL_VERSION}" -t truemark/aws-sam-cli-pipe:node-14-${FULL_VERSION} -f pipe.Dockerfile .
            - docker tag truemark/aws-sam-cli-pipe:node-14-${FULL_VERSION} truemark/aws-sam-cli-pipe:node-14-${SAM_VERSION}
            - docker tag truemark/aws-sam-cli-pipe:node-14-${FULL_VERSION} truemark/aws-sam-cli-pipe:node-14

#            - docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_PASS
#            - docker push truemark/aws-sam-cli
#            - docker push truemark/aws-sam-cli-pipe
