pipelines:
  branches:
    master:
      - parallel:
          - step:
              name: Build Base
              services:
                - docker
              script:
                - docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_PASS
                - docker build -t $DOCKER_IMAGE_NAME:$BITBUCKET_BUILD_NUMBER --target base .
                - docker tag $DOCKER_IMAGE_NAME:$BITBUCKET_BUILD_NUMBER $DOCKER_IMAGE_NAME:latest
                - docker push $DOCKER_IMAGE_NAME:$BITBUCKET_BUILD_NUMBER
                - docker push $DOCKER_IMAGE_NAME:latest
          - step:
              name: Build Golang
              services:
                - docker
              script:
                - docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_PASS
                - docker build -t $DOCKER_IMAGE_NAME:$BITBUCKET_BUILD_NIMBER-golang --target golang .
                - docker tag $DOCKER_IMAGE_NAME:$BITBUCKET_BUILD_NUMBER-golang $DOCKER_IMAGE_NAME:golang
                - docker push $DOCKER_IMAGE_NAME:$BITBUCKET_BUILD_NUMBER-golang
                - docker push $DOCKER_IMAGE_NAME:golang
