pipelines:
  branches:
    master:
      - step:
          name: Build
          services:
            - docker
          script:
            - docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_PASS
            - docker build -t $DOCKER_IMAGE_NAME:$BITBUCKET_BUILD_NUMBER .
            - docker tag $DOCKER_IMAGE_NAME:$BITBUCKET_BUILD_NUMBER $DOCKER_IMAGE_NAME:latest
            - docker push $DOCKER_IMAGE_NAME:$BITBUCKET_BUILD_NUMBER
            - docker push $DOCKER_IMAGE_NAME:latest
