name: beta

on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "${{ secrets.AWS_ASSUME_ROLE }}"
          aws-region: "us-east-1"
      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      - name: Setup Buildx Remote Docker
        id: buildx
        uses: truemark/aws-buildx-remote-docker-instance-action@v4
        with:
          security-group-id: "${{ vars.SECURITY_GROUP_ID }}"
          subnet-id: "${{ vars.SUBNET_ID }}"
          instance-profile: "${{ vars.INSTANCE_PROFILE }}"
          region: "us-east-2"
      - name: Build Base Image
        run: |
          docker buildx build \
          --push \
          --platform linux/arm64,linux/amd64 \
          -t truemark/aws-sam-cli:beta \
          --target base .
      - name: Copy beta to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-sam-cli:beta"
          dest-image: "docker://public.ecr.aws/truemark/aws-sam-cli:beta"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Build Go Image
        run: |
          docker buildx build \
          --push \
          --platform linux/arm64,linux/amd64 \
          -t truemark/aws-sam-cli:beta-go \
          --target go .
      - name: Copy beta-go to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-sam-cli:beta-go"
          dest-image: "docker://public.ecr.aws/truemark/aws-sam-cli:beta-go"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Build .NET 6 Image \
        run: |
          docker buildx build \
          --push \
          --platform linux/arm64,linux/amd64 \
          -t truemark/aws-sam-cli:beta-dotnet6 \
          --target dotnet6 .
      - name: Copy beta-dotnet6 to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-sam-cli:beta-dotnet6"
          dest-image: "docker://public.ecr.aws/truemark/aws-sam-cli:beta-dotnet6"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Build .NET 7 Image \
        run: |
          docker buildx build \
          --push \
          --platform linux/arm64,linux/amd64 \
          -t truemark/aws-sam-cli:beta-dotnet7 \
          --target dotnet7 .
      - name: Copy beta-dotnet7 to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-sam-cli:beta-dotnet7"
          dest-image: "docker://public.ecr.aws/truemark/aws-sam-cli:beta-dotnet7"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Build Node 18 Image \
        run: |
          docker buildx build \
          --push \
          --platform linux/arm64,linux/amd64 \
          -t truemark/aws-sam-cli:beta-node-18 \
          --target node18 .
      - name: Copy beta-node-18 to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-sam-cli:beta-node-18"
          dest-image: "docker://public.ecr.aws/truemark/aws-sam-cli:beta-node-18"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
