name: release

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 15 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Base Image
        run: |
          docker buildx build \
            --push \
            --platform linux/amd64 \
            -t truemark/aws-sam-cli:latest .
      - name: Build Golang Image
        run: |
          docker buildx build \
            --push \
            --platform linux/amd64 \
            --build-arg SOURCE_IMAGE="truemark/aws-sam-cli:latest" \
            -f golang.Dockerfile \
            -t truemark/aws-sam-cli:golang .
      - name: Build .NET 3.1 Image \
        run: |
          docker buildx build \
            --push \
            --platform linux/amd64 \
            --build-arg SOURCE_IMAGE="truemark/aws-sam-cli:latest" \
            -f netcore-3.1.Dockerfile \
            -t truemark/aws-sam-cli:netcore-3.1 .
      - name: Build Node 14 Image \
        run: |
          docker buildx build \
            --push \
            --platform linux/amd64 \
            --build-arg SOURCE_IMAGE="truemark/aws-sam-cli:latest" \
            -f node-14.Dockerfile \
            -t truemark/aws-sam-cli:node-14 .
      - name: Build Python 3.9 Image \
        run: |
          docker buildx build \
            --push \
            --platform linux/amd64 \
            --build-arg SOURCE_IMAGE="truemark/aws-sam-cli:latest" \
            -f python-3.9.Dockerfile \
            -t truemark/aws-sam-cli:python-3.9 .
